### ISSUE TITLE
Can't Use Android Back Button and Then Resume

### ISSUE THREAD

**Issue by BillyMartin1964** [jonathanpeppers/glidex#5]
**I never had this error until I installed GlideX.Forms and it went away on uninstall and reboot.**

Unhandled Exception:

Java.Lang.IllegalArgumentException: You cannot start a load for a destroyed activity occurred

**Here's a 2016 Glide Issue:**
[Glide issue](https://github.com/bumptech/glide/issues/1484)

**And here's my output:**

[GlideXError.txt](https://github.com/jonathanpeppers/glidex/files/2292142/GlideXError.txt)

**Comment by jonathanpeppers** [comment]
Did the link not paste?

I’ll search myself, perhaps they have a release of glide we can update to.

**Comment by BillyMartin1964** [comment]
@jonathanpeppers , Just emailed the link to your gmail

**Comment by jonathanpeppers** [comment]
Oh the markdown did something funny, I see:
```
[Text was missing here](https://github.com/bumptech/glide/issues/1484)
```

**Comment by jonathanpeppers** [comment]
I'm putting an update on NuGet, I'll keep this open until we confirm it fixes it.

I can't reproduce it myself (even the same app as @BillyMartin1964), 😞

**Comment by BillyMartin1964** [comment]
The update stopped the crashing, but for some reason, I cannot get an image on my starting page while using GlideX.

 

It’s in a MasterDetail Page. Please try to put an image on that page and let me know. The one I wanted to use is in the drawables. 

 

sunsetfishingbordered.png

**Comment by jonathanpeppers** [comment]
@BillyMartin1964 are you seeing any log messages with the `glidex` tag that was added?

https://github.com/jonathanpeppers/glidex/commit/81dac9bf07abc3a007aa5b232a678c4674916220

**Comment by BillyMartin1964** [comment]
Were you able to see the image @jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
> are you seeing any log messages with the glidex tag that was added?

> https://github.com/jonathanpeppers/glidex/commit/81dac9bf07abc3a007aa5b232a678c4674916220

**Comment by jonathanpeppers** [comment]
I think this issue was likely fixed at some point by the extra checks in this method: https://github.com/jonathanpeppers/glidex/blob/f3132f4bd3701deb27c4ea1c206223dc39a1a5a1/glidex.forms/GlideExtensions.cs#L88

You might try the current preview: https://www.nuget.org/packages/glidex.forms/2.0.0-pre1

I will be releasing an update as stable soon, I think.

**Comment by BillyMartin1964** [comment]
I tried it again after updating to xF 4 and still the same. At this point I'm pretty much over it. Sorry. Hope you get everything figured out. Thanks for your time.
